# Generated by Django 2.2.13 on 2021-08-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_libro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
