# Generated by Django 2.2.13 on 2021-08-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20210805_2357'),
        ('usuario', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
